# Branch to update (optional; defaults to master)
backend:
  name: git-gateway # Replace 'github' with your preferred backend provider
  branch: main # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: 'static/images' # Media files will be stored in the repo under static/uploads
public_folder: '/images' # The src attribute for uploaded media will begin with /uploads

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/lib/posts' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}'
    fields:
      - { label: 'Blog Name & Title add', name: 'title', widget: 'string' }
      - { label: 'date', name: 'date', widget: 'datetime' }
      - { label: 'updated', name: 'updated', widget: 'datetime' }
      - name: categories
        label: Categories
        widget: categories
        separator: __

      - { label: 'coverImageo', name: 'coverImage', widget: 'image' }
      - { label: 'coverWidth', name: 'coverWidth', widget: 'number' }
      - { label: 'coverHeight', name: 'coverHeight', widget: 'number' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'excerpt', name: 'excerpt', widget: 'string' }

  - name: 'items'
    label: 'Items'
    folder: 'src/lib/items'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string' }
      - { name: 'description', label: 'Description', widget: 'string' }
      - { name: 'imageUrl', label: 'Image URL', widget: 'string' }
      - { name: 'content', label: 'Content', widget: 'markdown' }
    format: 'json' # Set the format to JSON
